# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Multimer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Multimer
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxAppState'
  pod 'RxAnimated'
  pod 'Google-Mobile-Ads-SDK'
  pod 'lottie-ios'
  pod 'ReactorKit'

  target 'MultimerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MultimerUITests' do
    # Pods for testing
  end

end
